id: P000633
initial_creation_type: ocr
source_metadata:
  id: bdr:W19680
  title: རྩོམ་ཡིག་གསེར་གྱི་སྦྲམ་བུ
  author: ''
  volumes:
    ebfb281c75574f6087ee66b5f039688a:
      image_group_id: I4845
      title: ''
      volume_number: 1
      total_pages: 727
    86712d8d990046e5b1dc4ce04fa067ba:
      image_group_id: I4846
      title: ''
      volume_number: 2
      total_pages: 724
    faf67e7ac7114e21934ff24e2bd7dea4:
      image_group_id: I4847
      title: ''
      volume_number: 3
      total_pages: 816
